# Generated by Django 5.1.4 on 2025-01-14 14:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be paid for this milestone', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
